import type { WeaveMDApi } from '../../main/preload';
import type {
  AccountInfo,
  IFile,
  IHistoryEntry,
  ISettings,
  IUser,
  IUserPublic,
  LanguageType,
  ThemeType,
} from '../../shared/types';
import { validatePassword, validateUsername } from './validators';

type ApiResult<T = unknown> = {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
};

type UsernameCheckResult = {
  available: boolean;
  message: string;
};

type BrowserMockState = {
  users: IUser[];
  files: IFile[];
  historyEntries: IHistoryEntry[];
  settings: ISettings[];
  sessions: Array<{
    token: string;
    userId: string;
    createdAt: string;
  }>;
  importedFileSeed: number;
  isMaximized: boolean;
};

const MOCK_STORAGE_KEY = 'weavemd_browser_mock_v1';
const DEFAULT_THEME: ThemeType = 'light-header';
const DEFAULT_LANGUAGE: LanguageType = 'zh-CN';
const BRIDGE_UNAVAILABLE_MESSAGE =
  'Electron bridge is unavailable in browser preview mode. Using interactive local mock.';
const DEFAULT_WELCOME_FILE_NAME = 'welcome.md';
const DEFAULT_WELCOME_CONTENT = `# Welcome to WeaveMD

This browser preview runs on a local mock bridge instead of Electron.

## What works here

- Register and log in with local mock accounts
- Create, open, edit, save, and delete files
- Browse file history from the History panel
- Persist theme and language settings per account

## Try this

1. Create a new file from the top bar
2. Edit content in Monaco
3. Wait for auto-save or trigger save by switching files
4. Open History to jump between saved files
`;
const IMPORT_FALLBACK_TEMPLATE = `# Imported Preview File

This file was generated by the browser mock bridge because the local file picker
is unavailable in the current preview environment.

- You can still edit and save it into mock history.
- Real Electron IPC will replace this behavior in the desktop app.
`;

const createEmptyState = (): BrowserMockState => ({
  users: [],
  files: [],
  historyEntries: [],
  settings: [],
  sessions: [],
  importedFileSeed: 1,
  isMaximized: false,
});

const nowIso = () => new Date().toISOString();

const createId = (prefix: string) => {
  const randomPart =
    typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function'
      ? crypto.randomUUID()
      : `${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;

  return `${prefix}_${randomPart}`;
};

const toPublicUser = (user: IUser): IUserPublic => ({
  id: user.id,
  username: user.username,
  createdAt: user.createdAt,
  lastLogin: user.lastLogin,
});

const createSettingsRecord = (userId: string): ISettings => ({
  id: createId('settings'),
  userId,
  theme: DEFAULT_THEME,
  language: DEFAULT_LANGUAGE,
  customColors: null,
});

const createHistoryEntry = (fileId: string, version: number, content: string): IHistoryEntry => ({
  id: createId('history'),
  fileId,
  version,
  diff: content,
  savedAt: nowIso(),
});

const normalizeUsername = (username: string) => username.trim().toLowerCase();

const loadState = (): BrowserMockState => {
  if (typeof window === 'undefined') {
    return createEmptyState();
  }

  try {
    const raw = window.localStorage.getItem(MOCK_STORAGE_KEY);
    if (!raw) {
      return createEmptyState();
    }

    const parsed = JSON.parse(raw) as Partial<BrowserMockState>;
    return {
      users: Array.isArray(parsed.users) ? parsed.users : [],
      files: Array.isArray(parsed.files) ? parsed.files : [],
      historyEntries: Array.isArray(parsed.historyEntries) ? parsed.historyEntries : [],
      settings: Array.isArray(parsed.settings) ? parsed.settings : [],
      sessions: Array.isArray(parsed.sessions) ? parsed.sessions : [],
      importedFileSeed: typeof parsed.importedFileSeed === 'number' ? parsed.importedFileSeed : 1,
      isMaximized: Boolean(parsed.isMaximized),
    };
  } catch {
    return createEmptyState();
  }
};

const saveState = (state: BrowserMockState) => {
  if (typeof window === 'undefined') {
    return;
  }

  window.localStorage.setItem(MOCK_STORAGE_KEY, JSON.stringify(state));
};

const mutateState = <T>(updater: (state: BrowserMockState) => T): T => {
  const state = loadState();
  const result = updater(state);
  saveState(state);
  return result;
};

const ensureSettings = (state: BrowserMockState, userId: string): ISettings => {
  let record = state.settings.find((item) => item.userId === userId);
  if (!record) {
    record = createSettingsRecord(userId);
    state.settings.push(record);
  }
  return record;
};

const ensureWelcomeFile = (state: BrowserMockState, userId: string) => {
  const hasAnyFile = state.files.some((file) => file.userId === userId && !file.deletedAt);
  if (hasAnyFile) {
    return;
  }

  const createdAt = nowIso();
  const file: IFile = {
    id: createId('file'),
    userId,
    name: DEFAULT_WELCOME_FILE_NAME,
    content: DEFAULT_WELCOME_CONTENT,
    createdAt,
    modifiedAt: createdAt,
    deletedAt: null,
  };

  state.files.push(file);
  state.historyEntries.push(createHistoryEntry(file.id, 1, file.content));
};

const getVisibleFiles = (state: BrowserMockState, userId: string) =>
  state.files
    .filter((file) => file.userId === userId && !file.deletedAt)
    .sort((a, b) => b.modifiedAt.localeCompare(a.modifiedAt));

const getNextHistoryVersion = (state: BrowserMockState, fileId: string) =>
  state.historyEntries
    .filter((entry) => entry.fileId === fileId)
    .reduce((maxVersion, entry) => Math.max(maxVersion, entry.version), 0) + 1;

const createSuccessResult = <T>(data: T, message?: string): ApiResult<T> => ({
  success: true,
  data,
  message,
});

const createFailureResult = <T = unknown>(message: string): ApiResult<T> => ({
  success: false,
  error: message,
  message,
});

const triggerBrowserDownload = (content: string, filename: string, mimeType: string) => {
  if (typeof document === 'undefined' || typeof URL === 'undefined') {
    return false;
  }

  const blob = new Blob([content], { type: mimeType });
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = objectUrl;
  link.download = filename;
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(objectUrl);
  return true;
};

const readBrowserSelectedFile = (): Promise<
  ApiResult<{ path: string; name: string; content: string }>
> => {
  if (typeof document === 'undefined') {
    const name = `imported-preview-${Date.now().toString(36)}.md`;
    return Promise.resolve(
      createSuccessResult({
        path: name,
        name,
        content: IMPORT_FALLBACK_TEMPLATE,
      })
    );
  }

  return new Promise((resolve) => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.md,.markdown,.txt,text/markdown,text/plain';

    input.addEventListener('change', async () => {
      const selectedFile = input.files?.[0];
      if (!selectedFile) {
        resolve(createFailureResult('File selection cancelled.'));
        return;
      }

      try {
        const content = await selectedFile.text();
        resolve(
          createSuccessResult({
            path: selectedFile.name,
            name: selectedFile.name,
            content,
          })
        );
      } catch {
        resolve(createFailureResult('Failed to read the selected file.'));
      }
    });

    input.click();
  });
};

export const createNoopWeaveMDApi = (): WeaveMDApi => ({
  auth: {
    login: async (username, password) =>
      mutateState((state) => {
        const normalizedUsername = normalizeUsername(username);
        const user = state.users.find(
          (candidate) =>
            normalizeUsername(candidate.username) === normalizedUsername &&
            candidate.passwordHash === password
        );

        if (!user) {
          return createFailureResult('Invalid username or password.');
        }

        user.lastLogin = nowIso();
        ensureSettings(state, user.id);
        ensureWelcomeFile(state, user.id);

        const token = createId('mock-token');
        state.sessions = [
          { token, userId: user.id, createdAt: nowIso() },
          ...state.sessions.filter((session) => session.userId !== user.id),
        ].slice(0, 20);

        return createSuccessResult(
          {
            token,
            user: toPublicUser(user),
          },
          'Logged in with browser mock bridge.'
        );
      }),
    register: async (username, password) =>
      mutateState((state) => {
        const normalizedUsername = username.trim();
        const usernameValidation = validateUsername(normalizedUsername);
        if (!usernameValidation.valid) {
          return createFailureResult(usernameValidation.message);
        }

        const passwordValidation = validatePassword(password);
        if (!passwordValidation.valid) {
          return createFailureResult(passwordValidation.message);
        }

        const exists = state.users.some(
          (user) => normalizeUsername(user.username) === normalizeUsername(normalizedUsername)
        );
        if (exists) {
          return createFailureResult('Username is already taken.');
        }

        const createdAt = nowIso();
        const user: IUser = {
          id: createId('user'),
          username: normalizedUsername,
          passwordHash: password,
          createdAt,
          updatedAt: createdAt,
          lastLogin: null,
        };

        state.users.push(user);
        state.settings.push(createSettingsRecord(user.id));
        ensureWelcomeFile(state, user.id);

        return createSuccessResult(undefined, 'Account created in browser mock bridge.');
      }),
    checkUsername: async (username) => {
      const normalizedUsername = username.trim();
      const usernameValidation = validateUsername(normalizedUsername);
      if (!usernameValidation.valid) {
        return {
          available: false,
          message: usernameValidation.message,
        } satisfies UsernameCheckResult;
      }

      const state = loadState();
      const exists = state.users.some(
        (user) => normalizeUsername(user.username) === normalizeUsername(normalizedUsername)
      );

      return {
        available: !exists,
        message: exists ? 'Username is already taken.' : 'Username is available.',
      } satisfies UsernameCheckResult;
    },
    validateToken: async (token) => {
      const state = loadState();
      const session = state.sessions.find((candidate) => candidate.token === token);
      if (!session) {
        return createFailureResult('Token is invalid or expired.');
      }

      const user = state.users.find((candidate) => candidate.id === session.userId);
      if (!user) {
        return createFailureResult('Token user was not found.');
      }

      ensureWelcomeFile(state, user.id);
      ensureSettings(state, user.id);
      saveState(state);

      return createSuccessResult(toPublicUser(user));
    },
  },
  file: {
    create: async (userId, name) =>
      mutateState((state) => {
        const user = state.users.find((candidate) => candidate.id === userId);
        if (!user) {
          return createFailureResult('User not found.');
        }

        const createdAt = nowIso();
        const safeName = name.trim() || `untitled-${Date.now().toString(36)}.md`;
        const file: IFile = {
          id: createId('file'),
          userId,
          name: safeName,
          content: '',
          createdAt,
          modifiedAt: createdAt,
          deletedAt: null,
        };

        state.files.push(file);
        state.historyEntries.push(createHistoryEntry(file.id, 1, file.content));

        return createSuccessResult(file, 'File created in browser mock bridge.');
      }),
    open: async () => readBrowserSelectedFile(),
    save: async (fileId, content, userId) =>
      mutateState((state) => {
        const file = state.files.find(
          (candidate) =>
            candidate.id === fileId && candidate.userId === userId && candidate.deletedAt === null
        );

        if (!file) {
          return createFailureResult('File not found.');
        }

        file.content = content;
        file.modifiedAt = nowIso();

        state.historyEntries.push(
          createHistoryEntry(file.id, getNextHistoryVersion(state, file.id), content)
        );

        return createSuccessResult(file, 'File saved in browser mock bridge.');
      }),
    delete: async (fileId, userId) =>
      mutateState((state) => {
        const file = state.files.find(
          (candidate) =>
            candidate.id === fileId && candidate.userId === userId && candidate.deletedAt === null
        );

        if (!file) {
          return createFailureResult('File not found.');
        }

        file.deletedAt = nowIso();
        return createSuccessResult(undefined, 'File deleted from browser mock bridge.');
      }),
    list: async (userId) => {
      const state = loadState();
      return createSuccessResult(getVisibleFiles(state, userId));
    },
    get: async (fileId, userId) => {
      const state = loadState();
      const file = state.files.find(
        (candidate) =>
          candidate.id === fileId && candidate.userId === userId && candidate.deletedAt === null
      );

      if (!file) {
        return createFailureResult('File not found.');
      }

      return createSuccessResult(file);
    },
  },
  history: {
    list: async (fileId) => {
      const state = loadState();
      const entries = state.historyEntries
        .filter((entry) => entry.fileId === fileId)
        .sort((a, b) => b.version - a.version);
      return createSuccessResult(entries);
    },
    get: async (fileId, userId) => {
      const state = loadState();
      const file = state.files.find(
        (candidate) =>
          candidate.id === fileId && candidate.userId === userId && candidate.deletedAt === null
      );

      if (!file) {
        return createFailureResult('History file not found.');
      }

      const entries = state.historyEntries
        .filter((entry) => entry.fileId === fileId)
        .sort((a, b) => b.version - a.version);

      return createSuccessResult({
        file,
        entries,
      });
    },
  },
  settings: {
    get: async (userId) => {
      const state = loadState();
      const settings = ensureSettings(state, userId);
      saveState(state);
      return createSuccessResult(settings);
    },
    update: async (userId, settingsUpdate) =>
      mutateState((state) => {
        const settings = ensureSettings(state, userId);

        if (typeof settingsUpdate.theme === 'string') {
          settings.theme = settingsUpdate.theme as ThemeType;
        }
        if (typeof settingsUpdate.language === 'string') {
          settings.language = settingsUpdate.language as LanguageType;
        }
        if (
          typeof settingsUpdate.customColors === 'string' ||
          settingsUpdate.customColors === null
        ) {
          settings.customColors = settingsUpdate.customColors as string | null;
        }

        return createSuccessResult(settings, 'Settings saved in browser mock bridge.');
      }),
  },
  export: {
    md: async (content, filename) => {
      const safeName = filename.endsWith('.md') ? filename : `${filename}.md`;
      const downloaded = triggerBrowserDownload(content, safeName, 'text/markdown;charset=utf-8');
      return downloaded
        ? createSuccessResult({ filename: safeName }, 'Markdown exported from browser mock bridge.')
        : createFailureResult('Browser download is unavailable.');
    },
    docx: async (content, filename) => {
      const safeName = filename.endsWith('.docx') ? filename : `${filename}.docx`;
      const downloaded = triggerBrowserDownload(content, safeName, 'application/octet-stream');
      return downloaded
        ? createSuccessResult({ filename: safeName }, 'DOCX export placeholder downloaded.')
        : createFailureResult('Browser download is unavailable.');
    },
    pdf: async (content, filename) => {
      const safeName = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
      const downloaded = triggerBrowserDownload(content, safeName, 'application/pdf');
      return downloaded
        ? createSuccessResult({ filename: safeName }, 'PDF export placeholder downloaded.')
        : createFailureResult('Browser download is unavailable.');
    },
  },
  window: {
    minimize: async () => undefined,
    maximize: async () => {
      mutateState((state) => {
        state.isMaximized = true;
      });
    },
    unmaximize: async () => {
      mutateState((state) => {
        state.isMaximized = false;
      });
    },
    close: async () => undefined,
    isMaximized: async () => loadState().isMaximized,
  },
  dialog: {
    openFile: async () => readBrowserSelectedFile(),
    saveFile: async ({ defaultName }) =>
      createSuccessResult(
        {
          path: defaultName,
        },
        'Browser mock bridge uses automatic downloads instead of a native save dialog.'
      ),
  },
  account: {
    info: async (userId) => {
      const state = loadState();
      const user = state.users.find((candidate) => candidate.id === userId);
      if (!user) {
        return createFailureResult('Account not found.');
      }

      const activeFiles = getVisibleFiles(state, userId);
      const info: AccountInfo = {
        username: user.username,
        createdAt: user.createdAt,
        lastLogin: user.lastLogin,
        fileCount: activeFiles.length,
      };

      return createSuccessResult(info);
    },
    delete: async (userId) =>
      mutateState((state) => {
        const userIndex = state.users.findIndex((candidate) => candidate.id === userId);
        if (userIndex === -1) {
          return createFailureResult('Account not found.');
        }

        state.users.splice(userIndex, 1);
        state.settings = state.settings.filter((item) => item.userId !== userId);

        const deletedFileIds = state.files
          .filter((file) => file.userId === userId)
          .map((file) => file.id);
        state.files = state.files.filter((file) => file.userId !== userId);
        state.historyEntries = state.historyEntries.filter(
          (entry) => !deletedFileIds.includes(entry.fileId)
        );
        state.sessions = state.sessions.filter((session) => session.userId !== userId);

        return createSuccessResult(undefined, 'Account deleted from browser mock bridge.');
      }),
  },
});

let hasWarnedAboutFallback = false;

export const ensureWeaveMDApi = (): WeaveMDApi => {
  if (typeof window === 'undefined') {
    return createNoopWeaveMDApi();
  }

  if (window.weaveMD) {
    return window.weaveMD;
  }

  const fallbackApi = createNoopWeaveMDApi();
  window.weaveMD = fallbackApi;

  if (!hasWarnedAboutFallback) {
    console.warn(BRIDGE_UNAVAILABLE_MESSAGE);
    hasWarnedAboutFallback = true;
  }

  return fallbackApi;
};
